//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int Id { get; set; }
        public int Temperature { get; set; }
        public int GeneralState { get; set; }
        public int WindDirection { get; set; }
        public int WindSpeed { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public int RainChance { get; set; }
        public int CityId { get; set; }
        public string GeneralStateImageUrl { get; set; }
        public string GeneralStateCaption { get; set; }
        public string WindDirectionImageUrl { get; set; }
    
        public virtual City City { get; set; }
    }
}
