//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning
    {
        public int Id { get; set; }
        public string TItle { get; set; }
        public string Text { get; set; }
        public System.DateTimeOffset PublishedOn { get; set; }
        public string PublishedBy { get; set; }
    }
}
